spring:
  application:
    name: feign-app

  cloud:
    openfeign:
      client:
        config:
          external-service:
            url: http://localhost:3000
  feign:
    client:
      config:
        default:
          retry:
            max-attempts: 3
            max-period: 5
            period: 1